/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logins;

/**
 *
 * @author Akshay Kekunnaya
 */
public class admindashboard extends javax.swing.JFrame {

    /**
     * Creates new form admindashboard
     */
    public admindashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jaddstudent = new javax.swing.JButton();
        jviewstudents = new javax.swing.JButton();
        jfeepayment = new javax.swing.JButton();
        jaddamin = new javax.swing.JButton();
        jfeestructure = new javax.swing.JButton();
        jdeleteuser = new javax.swing.JButton();
        jlogout = new javax.swing.JButton();
        jdeleteuser1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Admin Dashboard");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jaddstudent.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jaddstudent.setText("Add Students");
        jaddstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddstudentActionPerformed(evt);
            }
        });

        jviewstudents.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jviewstudents.setText("View Students");
        jviewstudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jviewstudentsActionPerformed(evt);
            }
        });

        jfeepayment.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jfeepayment.setText("Pending Fee");
        jfeepayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfeepaymentActionPerformed(evt);
            }
        });

        jaddamin.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jaddamin.setText("Add Admin");
        jaddamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddaminActionPerformed(evt);
            }
        });

        jfeestructure.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jfeestructure.setText("Fee Structure");
        jfeestructure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfeestructureActionPerformed(evt);
            }
        });

        jdeleteuser.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jdeleteuser.setText("Delete Admin");
        jdeleteuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdeleteuserActionPerformed(evt);
            }
        });

        jlogout.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jlogout.setText("Logout");
        jlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlogoutActionPerformed(evt);
            }
        });

        jdeleteuser1.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jdeleteuser1.setText("Delete Student");
        jdeleteuser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdeleteuser1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jButton1.setText("Update Fee");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jdeleteuser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jfeepayment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jdeleteuser1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jviewstudents)
                            .addComponent(jaddstudent))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jaddamin, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jfeestructure, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jlogout)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jaddstudent)
                    .addComponent(jaddamin))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jviewstudents)
                    .addComponent(jfeestructure))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfeepayment)
                    .addComponent(jdeleteuser1))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jdeleteuser)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jlogout)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jaddstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddstudentActionPerformed
        AddStudents info = new AddStudents();
        info.setVisible(true);
    }//GEN-LAST:event_jaddstudentActionPerformed

    private void jaddaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddaminActionPerformed
        AddAdmin info = new AddAdmin();
        info.setVisible(true);
    }//GEN-LAST:event_jaddaminActionPerformed

    private void jviewstudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jviewstudentsActionPerformed
        ViewStudents info = new ViewStudents();
        info.setVisible(true);
    }//GEN-LAST:event_jviewstudentsActionPerformed

    private void jfeestructureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfeestructureActionPerformed
        FeeStructure info = new FeeStructure();
        info.setVisible(true);
    }//GEN-LAST:event_jfeestructureActionPerformed

    private void jfeepaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfeepaymentActionPerformed
         PendingFee info = new PendingFee();
         info.setVisible(true);
    }//GEN-LAST:event_jfeepaymentActionPerformed

    private void jdeleteuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdeleteuserActionPerformed
        DeleteAdmin info = new DeleteAdmin();
        info.setVisible(true);
    }//GEN-LAST:event_jdeleteuserActionPerformed

    private void jlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlogoutActionPerformed
       this.dispose();
    }//GEN-LAST:event_jlogoutActionPerformed

    private void jdeleteuser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdeleteuser1ActionPerformed
        DeleteStudent info = new DeleteStudent();
        info.setVisible(true);
    }//GEN-LAST:event_jdeleteuser1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admindashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jaddamin;
    private javax.swing.JButton jaddstudent;
    private javax.swing.JButton jdeleteuser;
    private javax.swing.JButton jdeleteuser1;
    private javax.swing.JButton jfeepayment;
    private javax.swing.JButton jfeestructure;
    private javax.swing.JButton jlogout;
    private javax.swing.JButton jviewstudents;
    // End of variables declaration//GEN-END:variables
}
